// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	Name                string `json:"name"`
	ProgrammingLanguage string `json:"programmingLanguage"`
}

type Mutation struct {
}

type NewAccount struct {
	Name                string `json:"name"`
	ProgrammingLanguage string `json:"programmingLanguage"`
}

type Query struct {
}
